// One entry per series, newest first. Sizes are longest side × width × thickness.
const SERIES = [
  {
    slug: 'e390', name: 'E390', released: 'Feb 2016',
    models: [['NW-E393', '4 GB'], ['NW-E394', '8 GB'], ['NW-E395', '16 GB']],
    screen: '1.77" color LCD, 128 × 160', battery: '35 h', port: 'Micro-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '92 × 43 × 10', weight: '39 g',
    software: 'None needed (drag and drop). Sony offers Music Center for PC (formerly Media Go).', firmware: 'Ver. 1.01',
    notes: 'The last E Series Walkman, with a flatter rectangular body, micro-USB charging, 35 hours of music playback, and side volume buttons and a hold switch again. It dropped video and plays only MP3, WMA, AAC and WAV (no FLAC). Sony was still selling it in 2024.',
    colors: ['black', 'red', 'blue'],
    images: [
      { file: 'e390-1-black-front.jpg', caption: 'NW-E390 in black with earbuds, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2016/05/20/sony-e-series-e390-walkman/' },
      { file: 'e390-2-black-blue-red.jpg', caption: 'NW-E390 in black, blue and red (red shown from the side)', credit: 'Sony', source: 'https://thewalkmanblog.com/2016/05/20/sony-e-series-e390-walkman/' },
      { file: 'e390-3-red-real.jpg', caption: 'NW-E390 series in red, real-world photo', credit: 'Sinlspeak, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_NW-E390_series_Walkman.jpg' },
      { file: 'e390-4-blue-front.jpg', caption: 'NW-E390 in blue with earbuds, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2016/05/20/sony-e-series-e390-walkman/' },
      { file: 'e390-5-black-in-hand.jpg', caption: 'NW-E394 in black, in hand on the home screen', credit: 'Sam Smart / Pocket-lint', source: 'https://www.pocket-lint.com/sony-walkman-e394-review/' },
      { file: 'e390-6-black-with-earbuds.jpg', caption: 'NW-E394 in black with its earbuds', credit: 'Sam Smart / Pocket-lint', source: 'https://www.pocket-lint.com/sony-walkman-e394-review/' },
    ],
  },
  {
    slug: 'e080', name: 'E080', released: 'Oct 2013', region: 'Japan',
    models: [['NW-E083', '4 GB']],
    screen: '2" color LCD, 240 × 320', battery: '36 h (30 h with noise cancelling)', port: 'WM-PORT',
    formats: 'ATRAC, ATRAC Lossless, MP3, WMA, AAC, WAV, FLAC, Apple Lossless', fm: 'Yes', size: '92.1 × 42.1 × 8', weight: '46 g',
    software: 'None needed (drag and drop). Media Go or x-APPLICATION (Windows), Content Transfer (Mac).', firmware: 'Ver. 1.02',
    notes: 'A larger, thinner body with a 2-inch screen that looks much like the NW-S780 sold at the same time, but with only 4 GB and three colors. It kept noise cancelling and added FLAC and Apple Lossless playback plus language-study tools such as slower playback and A-B repeat.',
    colors: ['red', 'black', 'blue'],
    images: [
      { file: 'e080-1-three-colors-front.jpg', caption: 'NW-E083 in red, black and blue, front', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/616398.html' },
      { file: 'e080-2-blue-earphones.jpg', caption: 'Blue NW-E083 with the included noise-cancelling earbuds', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/616398.html' },
      { file: 'e080-3-black-real.jpg', caption: 'Black NW-E083 showing the home menu', credit: 'Morita Akio, CC BY-SA 4.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:NW-E083.jpg' },
      { file: 'e080-4-red-in-hand.jpg', caption: 'Red NW-E083 in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/616398.html' },
      { file: 'e080-5-red-back.jpg', caption: 'Red NW-E083, back', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/616398.html' },
      { file: 'e080-6-speaker-docks.jpg', caption: 'NW-E083K speaker docks in black, blue and red', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/616398.html' },
    ],
  },
  {
    slug: 'e580', name: 'E580', released: 'Jul 2013',
    models: [['NWZ-E583', '4 GB'], ['NWZ-E584', '8 GB'], ['NWZ-E585', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '62–77 h audio, 13–14 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, HE-AAC, Apple Lossless, WAV, FLAC', fm: 'Yes', size: '92 × 41.7 × 7.5', weight: '49 g',
    software: 'None needed (drag and drop). Media Go (Windows) and Content Transfer (Mac) came on the player.', firmware: 'Ver. 1.02',
    notes: 'The first E Series Walkman that plays FLAC (and Apple Lossless) files, with digital noise cancelling through the bundled earbuds, a built-in voice recorder and up to 77 hours of music on a charge. Sony\'s European and Canadian stores sold it only in black.',
    colors: ['black'],
    images: [
      { file: 'e580-1-black-front.jpg', caption: 'NWZ-E580 in black, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e580-2-black-with-nc-earbuds.jpg', caption: 'NWZ-E580 in black with the bundled MDR-NC31 noise-cancelling earbuds', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e580-3-black-angled-closeup.jpg', caption: 'NWZ-E580, angled close-up of the screen and buttons', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e580-4-black-real-front.jpg', caption: 'NWZ-E585 in black, real-world front view', credit: 'Sinlspeak, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_NWZ-E585_Walkman.jpg' },
      { file: 'e580-5-next-to-e380.jpg', caption: 'NWZ-E580 in black (right) next to the smaller NWZ-E380 in red (left)', credit: 'Sony', source: 'https://www.slashgear.com/sony-walkman-e580-and-e380-take-on-apples-ipod-nano-10289702/' },
    ],
  },
  {
    slug: 'e380', name: 'E380', released: 'Jul 2013',
    models: [['NWZ-E383', '4 GB'], ['NWZ-E384', '8 GB'], ['NWZ-E385', '16 GB']],
    screen: '1.77" color LCD, 128 × 160', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.7 × 43.4 × 9.9', weight: '52 g',
    software: 'None needed (drag and drop). Media Go (Windows) and Content Transfer (Mac) came on the player.',
    notes: 'A cheaper, smaller sibling of the E580 with a 1.77-inch screen, 30 hours of music playback and a mini-USB port instead of the WM-PORT. It plays WMV video only and has no FLAC or noise cancelling; there are no separate volume keys or hold switch (volume is on the round button, and hold is a long press of the OPTION/PWR/HOLD button).',
    colors: ['black', 'red', 'blue', 'pink'],
    images: [
      { file: 'e380-1-red-front.jpg', caption: 'NWZ-E380 in red with earbuds, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e380-2-red-blue-black.jpg', caption: 'NWZ-E380 in red, blue and black', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e380-3-black-real-front.jpg', caption: 'NWZ-E383 in black, real-world front view', credit: 'Urban Versis 32, CC BY-SA 4.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:NWZ-E383.jpg' },
      { file: 'e380-4-black-back.jpg', caption: 'NWZ-E383 in black, back with the model label', credit: 'Urban Versis 32, CC BY-SA 4.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:NWZ-E383Back.jpg' },
    ],
  },
  {
    slug: 'e470-e570', name: 'E470 / E570', released: 'Jul 2012',
    models: [['NWZ-E473', '4 GB'], ['NWZ-E474', '8 GB'], ['NWZ-E475', '16 GB'], ['NWZ-E573', '4 GB'], ['NWZ-E574', '8 GB'], ['NWZ-E575', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30–36 h audio, 5–6 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '97.2 × 43.3 × 7.4', weight: '51 g',
    software: 'None needed (drag and drop). Media Go came on the player.',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e370', name: 'E370', released: 'Jul 2012',
    models: [['NWZ-E373', '4 GB'], ['NWZ-E374', '8 GB'], ['NWZ-E375', '16 GB']],
    screen: '1.77" color LCD, 128 × 160', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.7 × 43.4 × 9.9', weight: '52 g',
    software: 'None needed (drag and drop). Content Transfer came on the player.',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e060', name: 'E060', released: 'Feb 2012', region: 'Japan',
    models: [['NW-E062', '2 GB'], ['NW-E063', '4 GB']],
    screen: '1.4" color LCD, 128 × 160', battery: '30 h (24 h with noise cancelling)', port: 'WM-PORT',
    formats: 'ATRAC, ATRAC Lossless, MP3, WMA, AAC, WAV', fm: 'Yes', size: '77.5 × 35.5 × 9.35', weight: '37 g',
    software: 'x-APPLICATION (came on the player) for ATRAC and store purchases; drag and drop works for MP3, WMA and AAC.',
    notes: 'Nearly the same shape as the E050 but thinner and lighter, and the first E Series player with digital noise cancelling (the included earbuds have small microphones built in). The K models came with a matching speaker, not different earbuds.',
    colors: ['pink', 'blue', 'red', 'black'],
    images: [
      { file: 'e060-1-red-front.jpg', caption: 'Red NW-E060 with the included noise-cancelling earbuds, front', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/506834.html' },
      { file: 'e060-2-four-colors.jpg', caption: 'Pink, red, blue and black models', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/506834.html' },
      { file: 'e060-3-red-in-hand.jpg', caption: 'Red model in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/506834.html' },
      { file: 'e060-4-red-back.jpg', caption: 'Red model, back', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/506834.html' },
      { file: 'e060-5-red-in-pocket.jpg', caption: 'Red model tucked in a jeans pocket', credit: 'Sony', source: 'https://www.sony.jp/walkman/photogallery/e060series/index_mw.html' },
      { file: 'e060-6-speakers.jpg', caption: 'All four colors on the NW-E060K speaker docks', credit: 'Sony', source: 'https://www.sony.jp/walkman/photogallery/e060series/index_mw.html' },
    ],
  },
  {
    slug: 'e360', name: 'E360', released: 'Nov 2011',
    models: [['NWZ-E363', '4 GB'], ['NWZ-E364', '8 GB'], ['NWZ-E365', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.5 × 45 × 9.9', weight: '55 g',
    software: 'None needed (drag and drop). Content Transfer came on the player.',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e460', name: 'E460', released: 'Aug 2011',
    models: [['NWZ-E463', '4 GB'], ['NWZ-E464', '8 GB'], ['NWZ-E465', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '50 h audio, 10 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '96.8 × 45 × 10', weight: '58 g',
    software: 'None needed (drag and drop). Media Go came on the player.',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e050', name: 'E050', released: 'Oct 2010', region: 'Japan, some of Asia',
    models: [['NW-E052', '2 GB'], ['NW-E053', '4 GB']],
    screen: '1.4" color LCD, 128 × 160', battery: '30 h', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV (+ATRAC and ATRAC Lossless in Japan)', fm: 'Yes', size: '77 × 35.5 × 10.3', weight: '43 g',
    software: 'None needed (drag and drop). x-APPLICATION (Japan) or Content Transfer came on the player.',
    notes: 'The E Series switched from a USB stick to a small flat player with a 1.4-inch color screen and Sony\'s WM-PORT cable connector. In Japan it was also sold with a matching cone-shaped speaker stand (NW-E050K).',
    colors: ['blue', 'pink', 'silver', 'black'],
    images: [
      { file: 'e050-1-four-colors-front.jpg', caption: 'NW-E050 in blue, pink, silver and black, front', credit: 'Sony', source: 'https://www.sony.jp/walkman/photogallery/e050series/index_mw.html' },
      { file: 'e050-2-pink-and-blue-in-hand.jpg', caption: 'Pink and blue models in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/393620.html' },
      { file: 'e050-3-black-front-and-back.jpg', caption: 'Black model, front and back', credit: 'Sony', source: 'https://www.sony.jp/walkman/photogallery/e050series/index_mw.html' },
      { file: 'e050-4-blue-side.jpg', caption: 'Blue model, side view with the volume and hold buttons', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/393620.html' },
      { file: 'e050-5-black-on-desk.jpg', caption: 'Black model with earphones on a desk', credit: 'Sony', source: 'https://www.sony.jp/walkman/photogallery/e050series/index_mw.html' },
      { file: 'e050-6-speaker-stands.jpg', caption: 'All four colors on the cone-shaped speaker stands of the NW-E050K', credit: 'Sony', source: 'https://www.sony.jp/walkman/photogallery/e050series/index_mw.html' },
    ],
  },
  {
    slug: 'e350', name: 'E350', released: 'Sep 2010',
    models: [['NWZ-E353', '4 GB'], ['NWZ-E354', '8 GB'], ['NWZ-E355', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '50 h audio, 10 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '94.7 × 44 × 9.7', weight: '58 g',
    software: 'None needed (drag and drop). Content Transfer came on the player.',
    notes: 'A cheaper version of the E450, sold mainly in the US and parts of Asia. It keeps the 50-hour battery, SensMe channels, lyrics display and karaoke mode, but has no voice recording, plays only WMV video, and uses a standard mini-USB port instead of WM-PORT.',
    colors: ['black', 'red', 'blue'],
    images: [
      { file: 'e350-1-three-colors.jpg', caption: 'NWZ-E350 series in blue, red and black', credit: 'Sony (press photo via Engadget)', source: 'https://www.engadget.com/2010-08-11-sony-outs-nwz-e350-walkman.html' },
      { file: 'e350-2-black-earphones.jpg', caption: 'NWZ-E353 in black with the included earbuds', credit: 'Sony (product image via ObsoleteSony)', source: 'https://www.obsoletesony.com/networkwalkman/nwz-e353/' },
      { file: 'e350-3-blue-earphones.jpg', caption: 'NWZ-E354 in blue with the included earbuds', credit: 'Sony (product image via ObsoleteSony)', source: 'https://www.obsoletesony.com/networkwalkman/nwz-e354/' },
      { file: 'e350-4-red-earphones.jpg', caption: 'NWZ-E353 in red, front, with earbuds', credit: 'Sony India (archived product page)', source: 'https://web.archive.org/web/20101130052351/http://www.sony.co.in/product/nwz-e353' },
    ],
  },
  {
    slug: 'e450', name: 'E450', released: 'Jul 2010',
    models: [['NWZ-E453', '4 GB'], ['NWZ-E454', '8 GB'], ['NWZ-E455', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '50 h audio, 10 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '94.7 × 44 × 9.7', weight: '58 g',
    software: 'None needed (drag and drop). Content Transfer came on the player; Media Go also works.',
    notes: 'The 2010 model that added karaoke mode (it turns down the singer\'s voice), scrolling lyrics from .lrc files and SensMe mood channels. Sony rated it at 50 hours of music per charge; it kept WM-PORT and voice recording but dropped FM radio recording. Gold was sold in India only.',
    colors: ['black', 'red', 'blue', 'pink', 'green', 'gold'],
    images: [
      { file: 'e450-1-five-colors.jpg', caption: 'E450 series in pink, blue, green, red and black', credit: 'Sony (press photo via Sony Insider, archived)', source: 'https://web.archive.org/web/20180306153344/http://www.sonyinsider.com/2010/07/19/sony-walkman-e450-is-full-of-features-including-lyric-sync-and-karaoke-mode-2/' },
      { file: 'e450-2-black-front.jpg', caption: 'NWZ-E453 in black, front', credit: 'Pursinemi, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Walkman_NWZ-E453.png' },
      { file: 'e450-3-gold-earphones.jpg', caption: 'NWZ-E454 in gold (sold in India) with earbuds', credit: 'Sony India (archived product page)', source: 'https://web.archive.org/web/20101219082344/http://www.sony.co.in/product/nwz-e454' },
      { file: 'e450-4-in-hand.jpg', caption: 'E450 in black, held in hand', credit: 'Sony (press photo via Sony Insider, archived)', source: 'https://web.archive.org/web/20180306153344/http://www.sonyinsider.com/2010/07/19/sony-walkman-e450-is-full-of-features-including-lyric-sync-and-karaoke-mode-2/' },
      { file: 'e450-5-pink-usb.jpg', caption: 'NWZ-E453 in pink, plugged into a laptop over USB', credit: 'TechPatio', source: 'https://techpatio.com/2011/reviews/sony-walkman-nwz-e453-mp3-video-player' },
      { file: 'e450-6-pink-packaging.jpg', caption: 'NWZ-E453 in pink, in its retail box', credit: 'TechPatio', source: 'https://techpatio.com/2011/reviews/sony-walkman-nwz-e453-mp3-video-player' },
    ],
  },
  {
    slug: 'e340', name: 'E340', released: 'Oct 2009',
    models: [['NWZ-E343', '4 GB'], ['NWZ-E344', '8 GB'], ['NWZ-E345', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.3 × 44 × 9.3', weight: '54 g',
    software: 'None needed (drag and drop). Content Transfer came on the player.', firmware: 'Ver. 1.01',
    notes: 'A cheaper version of the E440, sold mainly in North America, that looks the same from the front. It has no voice or FM recording, plays only WMV video, and uses a standard mini-USB port instead of Sony\'s WM-PORT.',
    colors: ['black', 'red'],
    images: [
      { file: 'e340-1-black-front.jpg', caption: 'NWZ-E344 in black, front with the home menu', credit: 'Sony (product image via Newegg)', source: 'https://www.newegg.com/sony-nwz-e344blk-mp3-mp4-player/p/N82E16855158047' },
      { file: 'e340-2-red-earphones.jpg', caption: 'NWZ-E344 in red with the included earbuds', credit: 'Sony (product image via ObsoleteSony)', source: 'https://www.obsoletesony.com/networkwalkman/nwz-e344/' },
      { file: 'e340-3-red-front.jpg', caption: 'NWZ-E344 in red, front', credit: 'Newegg', source: 'https://www.newegg.com/p/N82E16855158048' },
      { file: 'e340-4-red-back.jpg', caption: 'NWZ-E344 in red, back', credit: 'Newegg', source: 'https://www.newegg.com/p/N82E16855158048' },
      { file: 'e340-5-packaging.jpg', caption: 'NWZ-E344 in its US retail package', credit: 'Newegg', source: 'https://www.newegg.com/sony-nwz-e344blk-mp3-mp4-player/p/N82E16855158047' },
    ],
  },
  {
    slug: 'e440', name: 'E440', released: 'Jul 2009',
    models: [['NWZ-E443', '4 GB'], ['NWZ-E444', '8 GB'], ['NWZ-E445', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30 h audio, 4–6 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '86.8 × 44 × 9.3', weight: '54 g',
    software: 'None needed (drag and drop). Content Transfer came on the player.', firmware: 'Ver. 1.01',
    notes: 'The 2009 follow-up to the E430: a little larger, with a silver ring around the controls and a two-tone front on the colored models. It added voice recording and FM radio recording, and some markets also sold it bundled with a matching speaker dock as the NWZ-E443K.',
    colors: ['black', 'red', 'pink'],
    images: [
      { file: 'e440-1-black-front.jpg', caption: 'NWZ-E443 in black, front', credit: 'Solomon203, CC BY-SA 3.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_Walkman_NWZ-E443F_face.jpg' },
      { file: 'e440-2-red-earphones.jpg', caption: 'NWZ-E443 in red with the included earbuds', credit: 'Sony (press photo via Flickr user Ronald Matta)', source: 'https://www.flickr.com/photos/ronaldi/3727702438/' },
      { file: 'e440-3-pink-speaker-dock.jpg', caption: 'NWZ-E443K in pink: the player docked in its color-matched speaker', credit: 'Sony (press photo via Flickr user Digital Chaos News)', source: 'https://www.flickr.com/photos/41093256@N07/3886866168/' },
      { file: 'e440-4-black-back.jpg', caption: 'NWZ-E443 in black, back with model label', credit: 'Solomon203, CC BY-SA 3.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_Walkman_NWZ-E443F_back.jpg' },
      { file: 'e440-5-in-hand.jpg', caption: 'NWZ-E443 in black, held in hand with the FM radio on screen', credit: 'Trusted Reviews', source: 'https://www.trustedreviews.com/reviews/sony-walkman-nwz-e443-4gb' },
      { file: 'e440-6-packaging.jpg', caption: 'NWZ-E443 in its retail box', credit: 'Trusted Reviews', source: 'https://www.trustedreviews.com/reviews/sony-walkman-nwz-e443-4gb' },
    ],
  },
  {
    slug: 'e040', name: 'E040', released: 'May 2009', region: 'Japan',
    models: [['NW-E042', '2 GB'], ['NW-E043', '4 GB'], ['NW-E044', '8 GB']],
    screen: '3-line color LCD', battery: '28–30 h', port: 'Built-in USB plug',
    formats: 'ATRAC, MP3, WMA, AAC, WAV', fm: 'Yes', size: '84.9 × 22.4 × 16.9', weight: '28 g',
    software: 'SonicStage V (required, came on the player), later x-APPLICATION. Windows only.',
    notes: 'The last stick-shaped E Series player, with a rounder body and the same swappable front panels as the E020 (two in the box, ten more sold separately). The music software came stored on the player itself instead of on a CD.',
    colors: ['mint green and pink', 'hot pink and purple', 'silver and white', 'gold and black', 'blue and orange'],
    images: [
      { file: 'e040-1-five-colors-front.jpg', caption: 'All five NW-E040 color sets, each with its spare panel and earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/152781.html' },
      { file: 'e040-2-blue-and-orange.jpg', caption: 'Blue model with its spare orange panel and black earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/152781.html' },
      { file: 'e040-3-pink-and-purple.jpg', caption: 'Hot pink model with its spare purple panel and white earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/152781.html' },
      { file: 'e040-4-mint-and-pink-angle.jpg', caption: 'Mint green and pink models, angled view', credit: 'Sony', source: 'https://www.sony.jp/walkman/products/NW-E040_series/' },
      { file: 'e040-5-wearable-case.jpg', caption: 'Silicone wearable case with strap (sold separately)', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/news/152781.html' },
      { file: 'e040-6-panel-display.jpg', caption: 'Extra Style-Up panels on display at the launch', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/news/152781.html' },
    ],
  },
  {
    slug: 'e430', name: 'E430', released: 'Aug 2008',
    models: [['NWZ-E435F', '2 GB'], ['NWZ-E436F', '4 GB'], ['NWZ-E438F', '8 GB']],
    screen: '2" color LCD, 240 × 320', battery: '45 h audio, 8 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '83.9 × 44 × 8.5', weight: '50 g',
    software: 'None needed (drag and drop). Came with Windows Media Player 11 and Content Transfer.', firmware: 'Ver. 1.02',
    notes: 'The first of the slim E Series players with a 2-inch color screen and video playback, replacing the older stick-shaped E Series outside Japan. It used Sony\'s WM-PORT connector and Sony rated it at about 45 hours of music per charge.',
    colors: ['black', 'red', 'pink', 'blue'],
    images: [
      { file: 'e430-1-black-front-back.jpg', caption: 'NWZ-E436F in black, front and back', credit: 'Sony (press photo via Trusted Reviews)', source: 'https://www.trustedreviews.com/reviews/sony-walkman-nwz-e436f-4gb' },
      { file: 'e430-2-four-colors.jpg', caption: 'NWZ-E436F in black, pink, red and blue', credit: 'Sony (press photo via Trusted Reviews)', source: 'https://www.trustedreviews.com/reviews/sony-walkman-nwz-e436f-4gb' },
      { file: 'e430-3-black-angle.jpg', caption: 'NWZ-E436F in black, angled view', credit: 'Sony (press photo via Trusted Reviews)', source: 'https://www.trustedreviews.com/reviews/sony-walkman-nwz-e436f-4gb' },
      { file: 'e430-4-red-in-hand.jpg', caption: 'NWZ-E436F in red, held in hand with the home menu on screen', credit: 'Dave Winer, CC BY-SA 2.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_got_it_right_--_the_new_Walkman_is_grreat!.jpg' },
      { file: 'e430-5-black-earphones.jpg', caption: 'NWZ-E436F in black with the included earbuds', credit: 'Sony (product image via ObsoleteSony)', source: 'https://www.obsoletesony.com/networkwalkman/nwz-e436f/' },
    ],
  },
  {
    slug: 'e020', name: 'E020', released: 'Mar 2008', region: 'Japan (NWD-E02x elsewhere)',
    models: [['NW-E023F', '1 GB'], ['NW-E025F', '2 GB'], ['NW-E026F', '4 GB']],
    screen: '3-line color LCD', battery: '28–30 h', port: 'Built-in USB plug',
    formats: 'MP3, WMA, AAC (+ATRAC, WAV in Japan)', fm: 'Yes', size: '83.7 × 22.3 × 16.2', weight: '28 g',
    software: 'Japan: SonicStage CP. Elsewhere (NWD models): drag and drop, no software needed.',
    notes: 'Still a USB stick, but the front panel and USB cap slide off and can be swapped. Each player came with two panels (so each color is really a pair), Sony sold 10 more designs, and unlike the E010 the Japanese models have FM radio.',
    colors: ['white and gold', 'black and silver', 'pink and light pink', 'blue and green', 'red and indigo'],
    images: [
      { file: 'e020-1-black-front.jpg', caption: 'Black NW-E020F with matching earphones, front', credit: 'Sony (via ASCII.jp)', source: 'https://ascii.jp/elem/000/000/109/109173/2/' },
      { file: 'e020-2-red-and-indigo-panels.jpg', caption: 'Red set: blazing red panel and the included indigo blue panel on a black body', credit: 'Sony (via ASCII.jp)', source: 'https://ascii.jp/elem/000/000/109/109173/2/' },
      { file: 'e020-3-blue-and-green-panels.jpg', caption: 'Blue set: ocean blue panel and the included green panel on a white body', credit: 'Sony (via ASCII.jp)', source: 'https://ascii.jp/elem/000/000/109/109173/2/' },
      { file: 'e020-4-white-in-hand.jpg', caption: 'White model in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20080220/sony2.htm' },
      { file: 'e020-5-swapping-panel.jpg', caption: 'Sliding the front panel off to swap it, with the USB cap removed', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20080220/sony2.htm' },
      { file: 'e020-6-black-silver-panel.jpg', caption: 'Black NW-E023F with the silver panel, playing a song', credit: 'Karl Baron (kalleboo), CC BY 2.0 (via Flickr)', source: 'https://www.flickr.com/photos/kalleboo/2438175266/' },
    ],
  },
  {
    slug: 'e010', name: 'E010', released: 'Apr 2007',
    models: [['NW-E013 / E013F', '1 GB'], ['NW-E015 / E015F', '2 GB'], ['NW-E016 / E016F', '4 GB']],
    screen: '3-line color LCD', battery: '30 h', port: 'Built-in USB plug',
    formats: 'ATRAC, MP3, WMA, AAC, WAV', fm: 'F models only (not sold in Japan)', size: '83.1 × 22.8 × 14.2', weight: '29 g',
    software: 'SonicStage CP (required, no drag and drop). Windows only.',
    notes: 'A USB-stick player: pull off the cap and it plugs straight into a computer, no cable needed. It replaced the one-color OLED screen of the earlier NW-E000 with a small color LCD that can show album art; the Japanese models (NW-E013/E015/E016) have no FM radio, while the F models sold in other countries do.',
    colors: ['black', 'violet', 'pink', 'blue', 'gold'],
    images: [
      { file: 'e010-1-five-colors-front.jpg', caption: 'NW-E010 series in all five colors (violet, blue, pink, gold, black), front', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20070411/sony.htm' },
      { file: 'e010-2-blue-earphones.jpg', caption: 'Blue model with the white earphones it came with', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20070411/sony.htm' },
      { file: 'e010-3-black-in-hand.jpg', caption: 'Black NW-E013 in hand, screen on', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20070420/np009.htm' },
      { file: 'e010-4-plugged-into-laptop.jpg', caption: 'Black NW-E013 plugged straight into a laptop\'s USB port', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20070420/np009.htm' },
      { file: 'e010-5-box.jpg', caption: 'NW-E013 retail box (Japan)', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20070420/np009.htm' },
      { file: 'e010-6-black-with-case.jpg', caption: 'Black NW-E013F next to a leather case', credit: 'Gene Wang, CC BY 2.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_Walkman_NW-E013F_20150309.jpg' },
    ],
  },
  {
    slug: 'e000', name: 'E000', released: 'Apr 2006',
    models: [['NW-E002 / E002F', '512 MB'], ['NW-E003 / E003F', '1 GB'], ['NW-E005 / E005F', '2 GB']],
    screen: '1-line OLED', battery: '28 h', port: 'Built-in USB plug',
    formats: 'ATRAC, MP3, WMA (+AAC in Japan)', fm: 'F models only', size: '79 × 24.8 × 13.6', weight: '25 g',
    software: 'SonicStage (required, no drag and drop). Windows only.', firmware: 'Ver. 2.01',
    notes: 'A small stick with a USB plug built into one end under a cap, so it plugs straight into a computer to load music and charge. It has a one-line OLED screen, a 3-minute charge gives about 3 hours of play, and the Japanese models were the first E Series players to play AAC files.',
    colors: ['black', 'violet', 'pink', 'blue', 'lime green', 'silver'],
    images: [
      { file: 'e000-1-six-colors.jpg', caption: 'NW-E000 series in silver, lime green, blue, pink, violet and black', credit: 'Sony', source: 'https://web.archive.org/web/20070616055611/http://www.sony-europe.com/PageView.do?section=en_EU_Press&pressrelease=1143471801922&site=odw_en_EU&page=PressReleaseDetail' },
      { file: 'e000-2-violet-in-hand-usb-plug.jpg', caption: 'NW-E000 in violet, held in hand with the USB cap off', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-3-violet-back.jpg', caption: 'NW-E000 in violet, back', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-4-black-with-earphones.jpg', caption: 'NW-E000 in black with the black earphones it came with', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-5-silver-angled.jpg', caption: 'NW-E005 in silver, angled view with the screen on', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-6-e003-violet-with-box.jpg', caption: 'NW-E003 in violet next to its box', credit: 'Ippukucho, CC BY 3.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:SonyWalkmanE003.JPG' },
    ],
  },
  {
    slug: 'e200-e300', name: 'E200 / E300', nickname: 'Bean', released: 'Oct 2005',
    models: [['NW-E205', '512 MB'], ['NW-E207', '1 GB'], ['NW-E303', '256 MB'], ['NW-E305', '512 MB'], ['NW-E307', '1 GB']],
    screen: '1-line OLED', battery: '50 h', port: 'Pop-out USB plug',
    formats: 'ATRAC, MP3', fm: 'E300 only', size: '68.2 × 39 × 24.1', weight: '45 g',
    software: 'SonicStage 3.2 (required). Windows only.',
    notes: 'Shaped like a jelly bean and made to be used with one hand, with a left-hand mode that flips the screen and buttons. Sliding a cover makes a USB plug pop out, so it can go straight into a computer without a cable; the colors were named after jelly bean flavors.',
    colors: ['white', 'blue', 'pink', 'black'],
    images: [
      { file: 'e200-e300-1-four-colors.jpg', caption: 'Walkman Bean in white, blue, pink and black', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-2-white-in-hand.jpg', caption: 'Walkman Bean in white, held in one hand', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-3-blue-with-earphones.jpg', caption: 'NW-E307 in Tropical Ice blue with matching earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-4-black.jpg', caption: 'NW-E307 in Licorice black', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-5-white-plugged-into-laptop.jpg', caption: 'Walkman Bean in white with its pop-out USB plug in a laptop', credit: 'Camilo Sanchez, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_Walkman_Bean_Plugged_To_Computer.jpg' },
      { file: 'e200-e300-6-pink-with-earphones.jpg', caption: 'NW-E307 in Cotton Candy pink with matching earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
    ],
  },
  {
    slug: 'e400-e500', name: 'E400 / E500', nickname: 'Core', released: 'Apr 2005',
    models: [['NW-E403', '256 MB'], ['NW-E405', '512 MB'], ['NW-E407', '1 GB'], ['NW-E503', '256 MB'], ['NW-E505', '512 MB'], ['NW-E507', '1 GB']],
    screen: '3-line OLED', battery: '50 h', port: 'Mini-USB',
    formats: 'ATRAC, MP3', fm: 'E500 only', size: '84.9 × 28.8 × 13.9', weight: '47 g',
    software: 'SonicStage 3 (required); MP3 File Manager added later. Windows only.', firmware: 'Ver. 2.00',
    notes: 'A slim stick with a mirror-like clear shell (Sony said the design idea was a perfume bottle), a 3-line OLED screen and a jog dial on the end. Its battery could get about 3 hours of play from a 3-minute charge; the E500 models add an FM radio.',
    colors: ['black', 'blue', 'red', 'green', 'silver', 'pink', 'gold'],
    images: [
      { file: 'e400-e500-1-e407-four-colors.jpg', caption: 'NW-E407 in blue, black, red and green', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e400-e500-2-e507-three-colors.jpg', caption: 'NW-E507 (with FM radio) in blue, silver and pink', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e400-e500-3-e505-silver-front.jpg', caption: 'NW-E505 in silver, front with the 3-line display on', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050413/zooma201.htm' },
      { file: 'e400-e500-4-e505-silver-back.jpg', caption: 'NW-E505 in silver, back', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050413/zooma201.htm' },
      { file: 'e400-e500-5-plugged-into-laptop.jpg', caption: 'NW-E500 series player connected to a laptop by USB cable', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e400-e500-6-mini-usb-port.jpg', caption: 'NW-E505 mini USB port under its cover at the bottom end', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050413/zooma201.htm' },
    ],
  },
  {
    slug: 'e100', name: 'E100', nickname: 'Circ', released: 'Mar 2005',
    models: [['NW-E103', '256 MB'], ['NW-E105', '512 MB'], ['NW-E107', '1 GB']],
    screen: '1-line LCD', battery: '70 h on one AAA', port: 'USB cable',
    formats: 'ATRAC, MP3', fm: 'No', size: '56.2 × 56.2 × 19.2', weight: '37 g with battery',
    software: 'SonicStage 3 (required); MP3 File Manager added later. Windows only.',
    notes: 'A round player about the size of a cookie that runs on one AAA battery instead of a built-in rechargeable one, good for about 70 hours. It was Sony\'s low-cost answer to the iPod shuffle, with a small backlit LCD and big press-down keys built into the front panel.',
    colors: ['silver', 'blue', 'red', 'orange', 'white'],
    images: [
      { file: 'e100-1-four-colors-front.jpg', caption: 'NW-E100 series in blue, red, silver and orange, front', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-2-silver-in-hand.jpg', caption: 'NW-E100 in silver, held in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-3-red-silver-back.jpg', caption: 'NW-E100 in red and silver, back side with the battery cover', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-4-white-in-hand.jpg', caption: 'NW-E107 in white, held in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-5-blue-armband.jpg', caption: 'NW-E100 in blue, in the optional armband', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
    ],
  },
  {
    slug: 'e55-e99', name: 'E53–E99', released: 'Jul 2004',
    models: [['NW-E53', '128 MB'], ['NW-E55', '128 MB'], ['NW-E73', '256 MB'], ['NW-E75', '256 MB'], ['NW-E95', '512 MB'], ['NW-E99', '1 GB']],
    screen: '1-line LCD', battery: '70 h on one AAA', port: 'Mini-USB',
    formats: 'ATRAC (MP3 on the E99 and European E95)', fm: 'No', size: '56 × 37.3 × 15', weight: '51 g with battery',
    software: 'SonicStage 2 (required); MP3 File Manager for MP3s. Windows only.',
    notes: 'A small square player with a jog dial on one corner that runs about 70 hours on one AAA battery. Every model in this group uses the same body, so the NW-E95 and NW-E99 look like the NW-E75 apart from color; MP3 support arrived late in 2004 with the NW-E99, the European NW-E95, and a free update for European NW-E55/E75 owners.',
    colors: ['silver', 'blue', 'red', 'white', 'black'],
    images: [
      { file: 'e55-e99-1-nw-e75-three-colors.jpg', caption: 'NW-E75 (Japan) in blue, red and white, front', credit: 'Sony', source: 'https://web.archive.org/web/20040811210410/http://www.ecat.sony.co.jp:80/audio/walkman/products/index.cfm?PD=17459&KM=NW-E75' },
      { file: 'e55-e99-2-nw-e75-silver.jpg', caption: 'NW-E75 in silver (the version sold outside Japan), front at an angle', credit: 'Alex Pappajohn, CC BY 2.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Network_Walkman_NW-E75.jpg' },
      { file: 'e55-e99-3-nw-e95-black.jpg', caption: 'NW-E95 in black, front', credit: 'Sony', source: 'https://web.archive.org/web/20040629163328/http://www.ecat.sony.co.jp:80/audio/walkman/products/index.cfm?PD=17457&KM=NW-E95' },
      { file: 'e55-e99-4-nw-e99-silver.jpg', caption: 'NW-E99 in silver, front', credit: 'Sony', source: 'https://web.archive.org/web/20050305181136/http://www.ecat.sony.co.jp:80/audio/walkman/products/index.cfm?PD=19386&KM=NW-E99' },
      { file: 'e55-e99-5-nw-e75-blue-in-hand.jpg', caption: 'NW-E75 in blue, in hand', credit: 'Impress AV Watch', source: 'https://av.watch.impress.co.jp/docs/20040615/sony.htm' },
      { file: 'e55-e99-6-nw-e99-battery-usb.jpg', caption: 'NW-E99 with the battery door open, showing the AAA battery and Mini-USB port', credit: 'Impress AV Watch', source: 'https://av.watch.impress.co.jp/docs/20041130/sony2.htm' },
    ],
  },
  {
    slug: 'e10', name: 'E7 / E10', released: 'Oct 2001',
    models: [['NW-E7', '64 MB'], ['NW-E10', '128 MB']],
    screen: 'Small round LCD (no song titles)', battery: '11 h (rechargeable)', port: 'USB charging cradle',
    formats: 'ATRAC, MP3', fm: 'No', size: '92.4 × 30.9 × 14.7', weight: '55 g',
    software: 'OpenMG Jukebox 2.2 (required, even for MP3). Windows only.',
    notes: 'The first Network Walkman that could play MP3 files, though they still had to be sent through Sony\'s OpenMG Jukebox software. It moved to a built-in rechargeable battery and came with a desktop cradle that both charges it and connects it to the PC over USB. The NW-E7 came in silver or blue; the NW-E10 only in titanium gray.',
    colors: ['silver', 'blue', 'titanium gray'],
    images: [
      { file: 'e10-1-nw-e10-cradle.jpg', caption: 'NW-E10 in titanium gray, standing in its USB cradle', credit: 'Sony', source: 'https://web.archive.org/web/20020831134731/http://www.ecat.sony.co.jp:80/audio/walkman/products/index.cfm?KM=NW-E10&PD=190' },
      { file: 'e10-2-nw-e7-silver-blue.jpg', caption: 'NW-E7 in silver and blue, in their cradles', credit: 'Sony', source: 'https://web.archive.org/web/20020831134619/http://www.ecat.sony.co.jp:80/audio/walkman/products/index.cfm?KM=NW-E7&PD=189' },
      { file: 'e10-3-nw-e7-blue-front.jpg', caption: 'NW-E7 in blue, front, with earphones', credit: 'Sony', source: 'https://web.archive.org/web/20050325021450/http://www.ecat.sony.co.jp/audio/walkman/products/feat.cfm?PD=189&KM=NW-E7' },
      { file: 'e10-4-nw-e7-in-hand.jpg', caption: 'NW-E7 in silver, in hand', credit: 'Sony', source: 'https://web.archive.org/web/20050325021450/http://www.ecat.sony.co.jp/audio/walkman/products/feat.cfm?PD=189&KM=NW-E7' },
      { file: 'e10-5-nw-e10-box.jpg', caption: 'NW-E10 retail box', credit: 'plasticmodel.yamatoblog.net', source: 'http://plasticmodel.yamatoblog.net/category14/sony_nw-e10' },
    ],
  },
  {
    slug: 'e8p', name: 'E8P', released: 'Apr 2001',
    models: [['NW-E8P', '64 MB']],
    screen: 'LCD', battery: '7 h on one AAA', port: 'Sony USB cable',
    formats: 'ATRAC', fm: 'No', size: '75 × 70 × 30 (each earpiece)', weight: '90 g',
    software: 'OpenMG Jukebox (required). Windows only.',
    notes: 'The whole player is built into a pair of ear-hook headphones: the right earpiece has the backlit screen and controls, and one AAA battery powers it. It has 64 MB of memory and plays only ATRAC3, like the NW-E3.',
    colors: ['titanium silver'],
    images: [
      { file: 'e8p-1-front.jpg', caption: 'NW-E8P, both earpieces', credit: 'Sony', source: 'https://web.archive.org/web/20021028025931/http://www.ecat.sony.co.jp:80/audio/walkman/products/index.cfm?PD=191&KM=NW-E8P' },
      { file: 'e8p-2-both-sides.jpg', caption: 'NW-E8P, right earpiece with the screen and left earpiece with the Walkman logo', credit: 'Sony (via Impress AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20010301/sony.htm' },
      { file: 'e8p-3-worn.jpg', caption: 'NW-E8P worn over the ear', credit: 'Sony (via Impress AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20010301/sony.htm' },
      { file: 'e8p-4-controls-closeup.jpg', caption: 'NW-E8P right earpiece, close-up of the volume, hold and jog controls', credit: 'Sony', source: 'https://web.archive.org/web/20040826094336/http://www.ecat.sony.co.jp/audio/walkman/products/feat.cfm?PD=191&KM=NW-E8P' },
    ],
  },
  {
    slug: 'e3', name: 'E2 / E3 / E5', released: 'Jun 2000',
    models: [['NW-E2', '32 MB'], ['NW-E3', '64 MB'], ['NW-E5', '96 MB']],
    screen: '1-line LCD', battery: '5 h on one AAA', port: 'Sony USB cable',
    formats: 'ATRAC', fm: 'No', size: '81 × 32 × 14.6', weight: '45 g with battery',
    software: 'OpenMG Jukebox (required). Windows only.',
    notes: 'The first Network Walkman with built-in memory, shaped like a cigarette lighter, with a shuttle switch on the end that you turn to skip and press to play. It ran on one AAA battery and only played ATRAC3 music sent from Sony\'s OpenMG Jukebox software. The NW-E5 was a limited chrome version (5,000 units in Japan), and the 32 MB NW-E2 was not sold in Japan.',
    colors: ['silver', 'blue', 'red', 'chrome'],
    images: [
      { file: 'e3-1-three-colors-front.jpg', caption: 'NW-E3 in red, silver and blue, front', credit: 'Sony', source: 'https://www.sony.jp/products/picture/NW-E3.jpg' },
      { file: 'e3-2-silver-front.jpg', caption: 'NW-E3 in silver, front, next to a AAA battery', credit: 'rud.dk, CC BY 2.5 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:SONY_WALKMAN_NW-E3.jpg' },
      { file: 'e3-3-silver-back.jpg', caption: 'NW-E3 in silver, back with the Walkman logo', credit: 'Impress Keitai Watch', source: 'https://k-tai.watch.impress.co.jp/cda/article/stapa/2939.html' },
      { file: 'e3-4-silver-shuttle-switch.jpg', caption: 'NW-E3 end view with the shuttle switch and headphone jack', credit: 'Impress Keitai Watch', source: 'https://k-tai.watch.impress.co.jp/cda/article/stapa/2939.html' },
      { file: 'e3-5-blue-in-hand.jpg', caption: 'NW-E3 in blue, in hand', credit: 'Saku (kadennote.blog.jp)', source: 'https://kadennote.blog.jp/archives/4101735.html' },
    ],
  },
];
