// One entry per series, newest first. Sizes are longest side × width × thickness.
const SERIES = [
  {
    slug: 'e390', name: 'E390', released: 'Feb 2016',
    models: [['NW-E393', '4 GB'], ['NW-E394', '8 GB'], ['NW-E395', '16 GB']],
    screen: '1.77" color LCD, 128 × 160', battery: '35 h', port: 'Micro-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '92 × 43 × 10', weight: '39 g',
    notes: 'The last E Series Walkman, with a flatter rectangular body, micro-USB charging, 35 hours of music playback, and side volume buttons and a hold switch again. It dropped video and plays only MP3, WMA, AAC and WAV (no FLAC). Sony was still selling it in 2024.',
    colors: ['black', 'red', 'blue'],
    images: [
      { file: 'e390-1-black-front.jpg', caption: 'NW-E390 in black with earbuds, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2016/05/20/sony-e-series-e390-walkman/' },
      { file: 'e390-2-black-blue-red.jpg', caption: 'NW-E390 in black, blue and red (red shown from the side)', credit: 'Sony', source: 'https://thewalkmanblog.com/2016/05/20/sony-e-series-e390-walkman/' },
      { file: 'e390-3-red-real.jpg', caption: 'NW-E390 series in red, real-world photo', credit: 'Sinlspeak, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_NW-E390_series_Walkman.jpg' },
      { file: 'e390-4-blue-front.jpg', caption: 'NW-E390 in blue with earbuds, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2016/05/20/sony-e-series-e390-walkman/' },
      { file: 'e390-5-black-in-hand.jpg', caption: 'NW-E394 in black, in hand on the home screen', credit: 'Sam Smart / Pocket-lint', source: 'https://www.pocket-lint.com/sony-walkman-e394-review/' },
      { file: 'e390-6-black-with-earbuds.jpg', caption: 'NW-E394 in black with its earbuds', credit: 'Sam Smart / Pocket-lint', source: 'https://www.pocket-lint.com/sony-walkman-e394-review/' },
    ],
  },
  {
    slug: 'e080', name: 'E080', released: 'Oct 2013', region: 'Japan',
    models: [['NW-E083', '4 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30–36 h', port: 'WM-PORT',
    formats: 'ATRAC, MP3, WMA, AAC, WAV', fm: 'Yes', size: '92.1 × 42.1 × 8', weight: '46 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e580', name: 'E580', released: 'Jul 2013',
    models: [['NWZ-E583', '4 GB'], ['NWZ-E584', '8 GB'], ['NWZ-E585', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '62–77 h audio, 13–14 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, HE-AAC, Apple Lossless, WAV, FLAC', fm: 'Yes', size: '92 × 41.7 × 7.5', weight: '49 g',
    notes: 'The first E Series Walkman that plays FLAC (and Apple Lossless) files, with digital noise cancelling through the bundled earbuds, a built-in voice recorder and up to 77 hours of music on a charge. Sony\'s European and Canadian stores sold it only in black.',
    colors: ['black'],
    images: [
      { file: 'e580-1-black-front.jpg', caption: 'NWZ-E580 in black, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e580-2-black-with-nc-earbuds.jpg', caption: 'NWZ-E580 in black with the bundled MDR-NC31 noise-cancelling earbuds', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e580-3-black-angled-closeup.jpg', caption: 'NWZ-E580, angled close-up of the screen and buttons', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e580-4-black-real-front.jpg', caption: 'NWZ-E585 in black, real-world front view', credit: 'Sinlspeak, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_NWZ-E585_Walkman.jpg' },
      { file: 'e580-5-next-to-e380.jpg', caption: 'NWZ-E580 in black (right) next to the smaller NWZ-E380 in red (left)', credit: 'Sony', source: 'https://www.slashgear.com/sony-walkman-e580-and-e380-take-on-apples-ipod-nano-10289702/' },
    ],
  },
  {
    slug: 'e380', name: 'E380', released: 'Jul 2013',
    models: [['NWZ-E383', '4 GB'], ['NWZ-E384', '8 GB'], ['NWZ-E385', '16 GB']],
    screen: '1.77" color LCD, 128 × 160', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.7 × 43.4 × 9.9', weight: '52 g',
    notes: 'A cheaper, smaller sibling of the E580 with a 1.77-inch screen, 30 hours of music playback and a mini-USB port instead of the WM-PORT. It plays WMV video only and has no FLAC or noise cancelling; there are no separate volume keys or hold switch (volume is on the round button, and hold is a long press of the OPTION/PWR/HOLD button).',
    colors: ['black', 'red', 'blue', 'pink'],
    images: [
      { file: 'e380-1-red-front.jpg', caption: 'NWZ-E380 in red with earbuds, front', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e380-2-red-blue-black.jpg', caption: 'NWZ-E380 in red, blue and black', credit: 'Sony', source: 'https://thewalkmanblog.com/2013/07/10/sony-introduces-the-new-e580-and-e380-walkmans/' },
      { file: 'e380-3-black-real-front.jpg', caption: 'NWZ-E383 in black, real-world front view', credit: 'Urban Versis 32, CC BY-SA 4.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:NWZ-E383.jpg' },
      { file: 'e380-4-black-back.jpg', caption: 'NWZ-E383 in black, back with the model label', credit: 'Urban Versis 32, CC BY-SA 4.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:NWZ-E383Back.jpg' },
    ],
  },
  {
    slug: 'e470-e570', name: 'E470 / E570', released: 'Jul 2012',
    models: [['NWZ-E473', '4 GB'], ['NWZ-E474', '8 GB'], ['NWZ-E475', '16 GB'], ['NWZ-E573', '4 GB'], ['NWZ-E574', '8 GB'], ['NWZ-E575', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30–36 h audio, 5–6 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '97.2 × 43.3 × 7.4', weight: '51 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e370', name: 'E370', released: 'Jul 2012',
    models: [['NWZ-E373', '4 GB'], ['NWZ-E374', '8 GB'], ['NWZ-E375', '16 GB']],
    screen: '1.77" color LCD, 128 × 160', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.7 × 43.4 × 9.9', weight: '52 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e060', name: 'E060', released: 'Feb 2012', region: 'Japan',
    models: [['NW-E062', '2 GB'], ['NW-E063', '4 GB']],
    screen: '1.4" color LCD, 128 × 160', battery: '30 h', port: 'WM-PORT',
    formats: 'ATRAC, MP3, WMA, AAC, WAV', fm: 'Yes', size: '77.5 × 35.5 × 9.1', weight: '37 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e360', name: 'E360', released: 'Nov 2011',
    models: [['NWZ-E363', '4 GB'], ['NWZ-E364', '8 GB'], ['NWZ-E365', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.5 × 45 × 9.9', weight: '55 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e460', name: 'E460', released: 'Aug 2011',
    models: [['NWZ-E463', '4 GB'], ['NWZ-E464', '8 GB'], ['NWZ-E465', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '50 h audio, 10 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '96.8 × 45 × 10', weight: '58 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e050', name: 'E050', released: 'Oct 2010', region: 'Japan, some of Asia',
    models: [['NW-E052', '2 GB'], ['NW-E053', '4 GB']],
    screen: '1.4" color LCD, 128 × 160', battery: '30 h', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV (+ATRAC in Japan)', fm: 'Yes', size: '77 × 35.5 × 10.3', weight: '43 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e350', name: 'E350', released: 'Aug 2010',
    models: [['NWZ-E353', '4 GB'], ['NWZ-E354', '8 GB'], ['NWZ-E355', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '50 h audio, 10 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '94.7 × 44 × 9.7', weight: '58 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e450', name: 'E450', released: 'Jul 2010',
    models: [['NWZ-E453', '4 GB'], ['NWZ-E454', '8 GB'], ['NWZ-E455', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '50 h audio, 10 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '95 × 44.1 × 10.4', weight: '58 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e340', name: 'E340', released: 'Dec 2009',
    models: [['NWZ-E343', '4 GB'], ['NWZ-E344', '8 GB'], ['NWZ-E345', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30 h audio, 4 h video', port: 'Mini-USB',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '87.3 × 44.6 × 9.7', weight: '54 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e440', name: 'E440', released: 'Jul 2009',
    models: [['NWZ-E443', '4 GB'], ['NWZ-E444', '8 GB'], ['NWZ-E445', '16 GB']],
    screen: '2" color LCD, 240 × 320', battery: '30 h audio, 4 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '86.8 × 44 × 9.3', weight: '54 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e040', name: 'E040', released: 'May 2009', region: 'Japan, some of Asia',
    models: [['NW-E042', '2 GB'], ['NW-E043', '4 GB'], ['NW-E044', '8 GB']],
    screen: '3-line color LCD', battery: '28–30 h', port: 'Built-in USB plug',
    formats: 'MP3, WMA, AAC, WAV (+ATRAC in Japan)', fm: 'Yes', size: '84.9 × 22.4 × 16.9', weight: '28 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e430', name: 'E430', released: 'Aug 2008',
    models: [['NWZ-E435F', '2 GB'], ['NWZ-E436F', '4 GB'], ['NWZ-E438F', '8 GB']],
    screen: '2" color LCD, 240 × 320', battery: '45 h audio, 8 h video', port: 'WM-PORT',
    formats: 'MP3, WMA, AAC, WAV', fm: 'Yes', size: '83.9 × 44 × 8.5', weight: '50 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e020', name: 'E020', released: 'Mar 2008', region: 'Japan (NWD-E02x elsewhere)',
    models: [['NW-E023F', '1 GB'], ['NW-E025F', '2 GB'], ['NW-E026F', '4 GB']],
    screen: '3-line color LCD', battery: '28–30 h', port: 'Built-in USB plug',
    formats: 'MP3, WMA, AAC (+ATRAC in Japan)', fm: 'Yes', size: '83.7 × 22.3 × 16.2', weight: '28 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e010', name: 'E010', released: 'Apr 2007',
    models: [['NW-E013 / E013F', '1 GB'], ['NW-E015 / E015F', '2 GB'], ['NW-E016 / E016F', '4 GB']],
    screen: '3-line color display', battery: '28–30 h', port: 'Built-in USB plug',
    formats: 'ATRAC, MP3, WMA, AAC', fm: 'F models only', size: '83.1 × 22.8 × 14.2', weight: '29 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e000', name: 'E000', released: 'Apr 2006',
    models: [['NW-E002 / E002F', '512 MB'], ['NW-E003 / E003F', '1 GB'], ['NW-E005 / E005F', '2 GB']],
    screen: '1-line OLED', battery: '28 h', port: 'Built-in USB plug',
    formats: 'ATRAC, MP3, WMA (+AAC in Japan)', fm: 'F models only', size: '79 × 24.8 × 13.6', weight: '25 g',
    notes: 'A small stick with a USB plug built into one end under a cap, so it plugs straight into a computer to load music and charge. It has a one-line OLED screen, a 3-minute charge gives about 3 hours of play, and the Japanese models were the first E Series players to play AAC files.',
    colors: ['black', 'violet', 'pink', 'blue', 'lime green', 'silver'],
    images: [
      { file: 'e000-1-six-colors.jpg', caption: 'NW-E000 series in silver, lime green, blue, pink, violet and black', credit: 'Sony', source: 'https://web.archive.org/web/20070616055611/http://www.sony-europe.com/PageView.do?section=en_EU_Press&pressrelease=1143471801922&site=odw_en_EU&page=PressReleaseDetail' },
      { file: 'e000-2-violet-in-hand-usb-plug.jpg', caption: 'NW-E000 in violet, held in hand with the USB cap off', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-3-violet-back.jpg', caption: 'NW-E000 in violet, back', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-4-black-with-earphones.jpg', caption: 'NW-E000 in black with the black earphones it came with', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-5-silver-angled.jpg', caption: 'NW-E005 in silver, angled view with the screen on', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20060525/sony1.htm' },
      { file: 'e000-6-e003-violet-with-box.jpg', caption: 'NW-E003 in violet next to its box', credit: 'Ippukucho, CC BY 3.0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:SonyWalkmanE003.JPG' },
    ],
  },
  {
    slug: 'e200-e300', name: 'E200 / E300', nickname: 'Bean', released: 'Oct 2005',
    models: [['NW-E205', '512 MB'], ['NW-E207', '1 GB'], ['NW-E303', '256 MB'], ['NW-E305', '512 MB'], ['NW-E307', '1 GB']],
    screen: '1-line OLED', battery: '50 h', port: 'Pop-out USB plug',
    formats: 'ATRAC, MP3', fm: 'E300 only', size: '68.2 × 39 × 24.1', weight: '45 g',
    notes: 'Shaped like a jelly bean and made to be used with one hand, with a left-hand mode that flips the screen and buttons. Sliding a cover makes a USB plug pop out, so it can go straight into a computer without a cable; the colors were named after jelly bean flavors.',
    colors: ['white', 'blue', 'pink', 'black'],
    images: [
      { file: 'e200-e300-1-four-colors.jpg', caption: 'Walkman Bean in white, blue, pink and black', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-2-white-in-hand.jpg', caption: 'Walkman Bean in white, held in one hand', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-3-blue-with-earphones.jpg', caption: 'NW-E307 in Tropical Ice blue with matching earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-4-black.jpg', caption: 'NW-E307 in Licorice black', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
      { file: 'e200-e300-5-white-plugged-into-laptop.jpg', caption: 'Walkman Bean in white with its pop-out USB plug in a laptop', credit: 'Camilo Sanchez, CC0 (via Wikimedia Commons)', source: 'https://commons.wikimedia.org/wiki/File:Sony_Walkman_Bean_Plugged_To_Computer.jpg' },
      { file: 'e200-e300-6-pink-with-earphones.jpg', caption: 'NW-E307 in Cotton Candy pink with matching earphones', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050825/sony1.htm' },
    ],
  },
  {
    slug: 'e400-e500', name: 'E400 / E500', nickname: 'Core', released: 'Apr 2005',
    models: [['NW-E403', '256 MB'], ['NW-E405', '512 MB'], ['NW-E407', '1 GB'], ['NW-E503', '256 MB'], ['NW-E505', '512 MB'], ['NW-E507', '1 GB']],
    screen: '3-line OLED', battery: '50 h', port: 'Mini-USB',
    formats: 'ATRAC, MP3', fm: 'E500 only', size: '84.9 × 28.8 × 13.9', weight: '47 g',
    notes: 'A slim stick with a mirror-like clear shell (Sony said the design idea was a perfume bottle), a 3-line OLED screen and a jog dial on the end. Its battery could get about 3 hours of play from a 3-minute charge; the E500 models add an FM radio.',
    colors: ['black', 'blue', 'red', 'green', 'silver', 'pink', 'gold'],
    images: [
      { file: 'e400-e500-1-e407-four-colors.jpg', caption: 'NW-E407 in blue, black, red and green', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e400-e500-2-e507-three-colors.jpg', caption: 'NW-E507 (with FM radio) in blue, silver and pink', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e400-e500-3-e505-silver-front.jpg', caption: 'NW-E505 in silver, front with the 3-line display on', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050413/zooma201.htm' },
      { file: 'e400-e500-4-e505-silver-back.jpg', caption: 'NW-E505 in silver, back', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050413/zooma201.htm' },
      { file: 'e400-e500-5-plugged-into-laptop.jpg', caption: 'NW-E500 series player connected to a laptop by USB cable', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e400-e500-6-mini-usb-port.jpg', caption: 'NW-E505 mini USB port under its cover at the bottom end', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050413/zooma201.htm' },
    ],
  },
  {
    slug: 'e100', name: 'E100', nickname: 'Circ', released: 'Mar 2005',
    models: [['NW-E103', '256 MB'], ['NW-E105', '512 MB'], ['NW-E107', '1 GB']],
    screen: '1-line LCD', battery: '70 h on one AAA', port: 'USB cable',
    formats: 'ATRAC, MP3', fm: 'No', size: '56.2 × 56.2 × 19.2', weight: '37 g with battery',
    notes: 'A round player about the size of a cookie that runs on one AAA battery instead of a built-in rechargeable one, good for about 70 hours. It was Sony\'s low-cost answer to the iPod shuffle, with a small backlit LCD and big press-down keys built into the front panel.',
    colors: ['silver', 'blue', 'red', 'orange', 'white'],
    images: [
      { file: 'e100-1-four-colors-front.jpg', caption: 'NW-E100 series in blue, red, silver and orange, front', credit: 'Sony (via AV Watch)', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-2-silver-in-hand.jpg', caption: 'NW-E100 in silver, held in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-3-red-silver-back.jpg', caption: 'NW-E100 in red and silver, back side with the battery cover', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-4-white-in-hand.jpg', caption: 'NW-E107 in white, held in hand', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
      { file: 'e100-5-blue-armband.jpg', caption: 'NW-E100 in blue, in the optional armband', credit: 'AV Watch', source: 'https://av.watch.impress.co.jp/docs/20050308/sony1.htm' },
    ],
  },
  {
    slug: 'e55-e99', name: 'E55–E99', released: 'Jul 2004',
    models: [['NW-E55', '128 MB'], ['NW-E73', '128 MB'], ['NW-E75', '256 MB'], ['NW-E95', '512 MB'], ['NW-E99', '1 GB']],
    screen: '1-line LCD', battery: '70 h on one AAA', port: 'Mini-USB',
    formats: 'ATRAC (E95/E99 add MP3)', fm: 'No', size: '56 × 37.3 × 15', weight: '40 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e10', name: 'E7 / E10', released: 'Oct 2001',
    models: [['NW-E7', '64 MB'], ['NW-E10', '128 MB']],
    screen: 'LCD', battery: '11 h (rechargeable)', port: 'Charging cradle',
    formats: 'ATRAC, MP3', fm: 'No', size: '92.4 × 30.9 × 14.7', weight: '55 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e8p', name: 'E8P', released: 'Apr 2001',
    models: [['NW-E8P', '64 MB']],
    screen: 'LCD', battery: '7 h on one AAA', port: 'Mini-USB',
    formats: 'ATRAC', fm: 'No', size: '—', weight: '90 g',
    notes: '', colors: [], images: [],
  },
  {
    slug: 'e3', name: 'E2 / E3 / E5', released: 'Jun 2000',
    models: [['NW-E2', '32 MB'], ['NW-E3', '64 MB'], ['NW-E5', '96 MB']],
    screen: '1-line LCD', battery: '5 h on one AAA', port: 'Cradle (USB)',
    formats: 'ATRAC', fm: 'No', size: '81 × 32 × 14.6', weight: '45 g',
    notes: '', colors: [], images: [],
  },
];
